# Generated by Django 5.2.3 on 2025-06-28 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('studio', models.CharField(max_length=100)),
                ('ratings', models.IntegerField(help_text='Rating out of 20', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('platforms', models.ManyToManyField(related_name='games', to='games.platform')),
            ],
            options={
                'ordering': ['-release_date', 'name'],
                'unique_together': {('name', 'studio')},
            },
        ),
    ]
